/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.1-30-g5935269

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   CO_OD.h; CO_OD.c
        Project File: SZHC-CSTS1A_20220523.eds
        File Version: 1

        Created:      2020/9/17 10:26:00
        Created By:   SZHC
        Modified:     2022/5/23 9:47:00
        Modified By:  SZHC

    Device Info:
        Vendor Name:  Shenzhen Huacheng Industrial Control Co.,Ltd.
        Vendor ID:    2347
        Product Name: CSTS1A
        Product ID:   5122

        Description:  SZHC CSTS1A EDS file
*******************************************************************************/

#ifndef CO_OD_H
#define CO_OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define CO_OD_CNT_ARR_1003 8
#define CO_OD_CNT_ARR_1010 1
#define CO_OD_CNT_ARR_1011 3
#define CO_OD_CNT_ARR_1016 4
#define CO_OD_CNT_ARR_1029 6
#define CO_OD_CNT_ARR_6091 2
#define CO_OD_CNT_ARR_6099 2
#define CO_OD_CNT_ARR_60C1 2
#define CO_OD_CNT_ARR_60C3 2


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint8_t x1001_errorRegister;
    uint32_t x1002_manufacturerStatusRegister;
    uint8_t x1003_pre_definedErrorField_sub0;
    uint32_t x1003_pre_definedErrorField[CO_OD_CNT_ARR_1003];
    uint32_t x1005_COB_ID_SYNC;
    uint32_t x1006_communicationCyclePeriod;
    char x1008_manufacturerDeviceName[26];
    char x1009_manufacturerHardwareVersion[5];
    char x100A_manufacturerSoftwareVersion[5];
    uint8_t x100B_deviceID;
    uint16_t x100C_guardTime;
    uint8_t x100D_lifeTimeFactor;
    uint32_t x100E_nodeGuardingID;
    uint8_t x1010_storeParameters_sub0;
    uint32_t x1010_storeParameters[CO_OD_CNT_ARR_1010];
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1011_restoreDefaultParameters[CO_OD_CNT_ARR_1011];
    uint32_t x1013_highResolutionTimeStamp;
    uint32_t x1014_COB_ID_EMCY;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[CO_OD_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t numberOfEntries;
        uint32_t vendorId1;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identityObject;
    struct {
        uint8_t maxSub_index;
        uint32_t COB_IDClientToServer;
        uint32_t COB_IDServerToClient;
        uint8_t node_IDOfTheSDOServer;
    } x1280_SDOClientParameter;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID1;
        uint8_t transmissionType;
    } x1400_receivePDO_CommunicationParameter0;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID1;
        uint8_t transmissionType;
    } x1401_receivePDO_CommunicationParameter1;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID1;
        uint8_t transmissionType;
    } x1402_receivePDO_CommunicationParameter2;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID1;
        uint8_t transmissionType;
    } x1403_receivePDO_CommunicationParameter3;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO_MappingEntry1;
        uint32_t PDO_MappingEntry2;
        uint32_t PDO_MappingEntry3;
        uint32_t PDO_MappingEntry4;
        uint32_t PDO_MappingEntry5;
        uint32_t PDO_MappingEntry6;
        uint32_t PDO_MappingEntry7;
        uint32_t PDO_MappingEntry8;
    } x1600_receivePDO_MappingParameter0;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO_MappingEntry1;
        uint32_t PDO_MappingEntry2;
        uint32_t PDO_MappingEntry3;
        uint32_t PDO_MappingEntry4;
        uint32_t PDO_MappingEntry5;
        uint32_t PDO_MappingEntry6;
        uint32_t PDO_MappingEntry7;
        uint32_t PDO_MappingEntry8;
    } x1601_receivePDO_MappingParameter1;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO_MappingEntry1;
        uint32_t PDO_MappingEntry2;
        uint32_t PDO_MappingEntry3;
        uint32_t PDO_MappingEntry4;
        uint32_t PDO_MappingEntry5;
        uint32_t PDO_MappingEntry6;
        uint32_t PDO_MappingEntry7;
        uint32_t PDO_MappingEntry8;
    } x1602_receivePDO_MappingParameter2;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO_MappingEntry1;
        uint32_t PDO_MappingEntry2;
        uint32_t PDO_MappingEntry3;
        uint32_t PDO_MappingEntry4;
        uint32_t PDO_MappingEntry5;
        uint32_t PDO_MappingEntry6;
        uint32_t PDO_MappingEntry7;
        uint32_t PDO_MappingEntry8;
    } x1603_receivePDO_MappingParameter3;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID1;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNC_StartValue;
    } x1800_transmitPDO_CommunicationParameter0;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID1;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNC_StartValue;
    } x1801_transmitPDO_CommunicationParameter1;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID1;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNC_StartValue;
    } x1802_transmitPDO_CommunicationParameter2;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID1;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
        uint8_t SYNC_StartValue;
    } x1803_transmitPDO_CommunicationParameter3;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO_MappingEntry1;
        uint32_t PDO_MappingEntry2;
        uint32_t PDO_MappingEntry3;
        uint32_t PDO_MappingEntry4;
        uint32_t PDO_MappingEntry5;
        uint32_t PDO_MappingEntry6;
        uint32_t PDO_MappingEntry7;
        uint32_t PDO_MappingEntry8;
    } x1A00_transmitPDO_MappingParameter0;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO_MappingEntry1;
        uint32_t PDO_MappingEntry2;
        uint32_t PDO_MappingEntry3;
        uint32_t PDO_MappingEntry4;
        uint32_t PDO_MappingEntry5;
        uint32_t PDO_MappingEntry6;
        uint32_t PDO_MappingEntry7;
        uint32_t PDO_MappingEntry8;
    } x1A01_transmitPDO_MappingParameter1;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO_MappingEntry1;
        uint32_t PDO_MappingEntry2;
        uint32_t PDO_MappingEntry3;
        uint32_t PDO_MappingEntry4;
        uint32_t PDO_MappingEntry5;
        uint32_t PDO_MappingEntry6;
        uint32_t PDO_MappingEntry7;
        uint32_t PDO_MappingEntry8;
    } x1A02_transmitPDO_MappingParameter2;
    struct {
        uint8_t numberOfEntries;
        uint32_t PDO_MappingEntry1;
        uint32_t PDO_MappingEntry2;
        uint32_t PDO_MappingEntry3;
        uint32_t PDO_MappingEntry4;
        uint32_t PDO_MappingEntry5;
        uint32_t PDO_MappingEntry6;
        uint32_t PDO_MappingEntry7;
        uint32_t PDO_MappingEntry8;
    } x1A03_transmitPDO_MappingParameter3;
    uint32_t x1F80_NMTStartup;
    struct {
        uint8_t maxSub_index;
        uint8_t P0_Node_ID;
        uint8_t P10_RS485_BDR_Selection;
        uint8_t P11_CAN_BDR_Selection;
    } x2000_communicationSettings;
    struct {
        uint8_t maxSub_index;
        uint16_t P281_1st_Control_Word;
        uint16_t P282_2nd_Control_Word;
        int32_t P290_Position_Target;
        int16_t P324_Speed_Target;
        int16_t P358_Torque_Tartget;
        uint16_t P97_Position_Max_Speed;
        uint16_t P98_Torque_Max_Speed;
        uint16_t P113_Acc_Time;
        uint16_t P114_Dec_Time;
        uint16_t P119_Torque_Limit;
        uint16_t P280_Com_Command;
    } x2001_servoControl;
    struct {
        uint8_t maxSub_index;
        uint16_t P2_Torque_Limit_Select;
        uint16_t P50_Interpolation_Mode_Select;
        uint16_t P58_Communication_Cycle_Period;
        uint16_t P59_Homing_Mode;
        uint16_t P71_Communication_Position_Control_Mode;
        uint16_t P90_Motor_Positive_Direction_Select;
        uint16_t P138_Overload_Level;
        uint16_t P139_Overspeed_Level;
    } x2002_basicControlConfig;
    struct {
        uint8_t maxSub_index;
        uint16_t P182_Motor_Code;
        uint16_t P184_Encoder_PPR;
        uint16_t P185_Encoder_Z_EAngle;
        uint16_t P186_Encoder_HALL101_EAngle;
        uint16_t P187_Motor_Pole_Pairs;
        uint16_t P188_Motor_Rated_Speed;
        uint16_t P190_Motor_Rated_Torque_PU;
        uint16_t P191_Motor_Max_Torque_PU;
        uint16_t P194_Motor_Rated_Volt;
    } x2003_motorSpecificSettings;
    struct {
        uint8_t maxSub_index;
        uint16_t P200_State_Machine;
        uint16_t P201_Control_Mode_Display;
        uint16_t P202_Error_Code;
        int32_t P212_Position_Demand_Value;
        int32_t P214_Position_Actual_Value;
        int16_t P220_Velocity_Demand_Value;
        int16_t P221_Velocity_Actual_Value;
        int16_t P223_Torque_Demand_Value;
        int16_t P224_Torque_Actual_Value;
        uint16_t P226_VBus;
        uint16_t P227_Temperature;
        int16_t P207_Reg_Ai_Value1;
        int16_t P208_Reg_Ai_Value2;
    } x2004_servoStatus;
    struct {
        uint8_t maxSub_index;
        uint16_t P18_Torque_Controller_Kp;
        uint16_t P19_Torque_Controller_Ki;
    } x2010_torqueController;
    struct {
        uint8_t maxSub_index;
        uint16_t P21_Velocity_Controller_Kp;
        uint16_t P22_Velocity_Controller_Ki;
    } x2011_velocityController;
    struct {
        uint8_t maxSub_index;
        uint16_t P20_Position_Controller_Kp;
        uint16_t P25_Velocity_Feed_Forward_Kf;
        uint16_t P21_Velocity_Controller_Kp;
        uint16_t P22_Velocity_Controller_Ki;
    } x2012_positionController;
    uint8_t x2100_errorStatusBits[1];
    uint16_t x603F_errorCode;
    uint16_t x6040_controlword;
    uint16_t x6041_statusword;
    int8_t x6060_modes_of_operation;
    int8_t x6061_modesOfOperationDisplay;
    int32_t x6062_positionDemandValue;
    int32_t x6063_positionActualValueOfEncoder;
    int32_t x6064_positionActualValue;
    uint32_t x6065_positionErrThreshold;
    uint32_t x6067_positionAtThreshold;
    int32_t x606B_velocity_demand_value;
    int32_t x606C_velocity_actual_value;
    uint16_t x606D_velocityAtThreshold;
    uint16_t x606F_velocityThreshold;
    int16_t x6071_targetTorque;
    int16_t x6072_maxTorque;
    int16_t x6074_torqueDemand;
    int16_t x6077_torqueActualValue;
    int32_t x607A_target_position;
    int32_t x607C_home_offset;
    uint8_t x607E_polarity;
    uint32_t x607F_max_velocity_limit;
    uint32_t x6081_profile_velocity;
    uint32_t x6083_profile_acceleration;
    uint32_t x6084_profile_deceleration;
    uint32_t x6085_quick_stop_deceleration;
    uint8_t x6091_gearRatio_sub0;
    int16_t x6091_gearRatio[CO_OD_CNT_ARR_6091];
    int8_t x6098_homing_method;
    uint8_t x6099_homing_speeds_sub0;
    int8_t x6099_homing_speeds[CO_OD_CNT_ARR_6099];
    int16_t x60C0_interpolation_sub_mode_select;
    uint8_t x60C1_interpolation_data_record_sub0;
    int32_t x60C1_interpolation_data_record[CO_OD_CNT_ARR_60C1];
    struct {
        uint8_t interpolation_time_period_number_of_entries;
        uint8_t interpolation_time_period_Interpolation_time_units1;
        int8_t interpolation_time_period_Interpolation_time_index;
    } x60C2_interpolation_time_period;
    uint8_t x60C3_interpolation_sync_definition_sub0;
    uint8_t x60C3_interpolation_sync_definition[CO_OD_CNT_ARR_60C3];
    struct {
        uint8_t interpolation_data_configuration_number_of_entries;
        uint32_t interpolation_data_configuration_Maximum_buffer_size1;
        uint32_t interpolation_data_configuration_Actual_buffer_size;
        uint8_t interpolation_data_configuration_Buffer_organization;
        uint16_t interpolation_data_configuration_Buffer_position;
        uint8_t interpolation_data_configuration_Size_of_data_record;
        uint8_t value_Description_Buffer_clear;
    } x60C4_interpolation_data_configuration;
    uint16_t x60E0_positiveTorqueLimitValue;
    uint16_t x60E1_negativeTorqueLimitValue;
    int32_t x60F4_following_error_actual_value;
    int32_t x60FC_position_demand_value;
    uint32_t x60FD_digital_inputs;
    int32_t x60FF_target_velocity;
    char x6504_drive_manufacturer[46];
} CO_OD_RAM_t;

typedef struct {
    uint32_t x1007_synchronousWindowLength;
    uint32_t x1012_COB_ID_TIME;
    uint16_t x1015_inhibitTimeEMCY;
    uint8_t x1019_synchronousCounterOverflowValue;
    uint8_t x1029_errorBehavior_sub0;
    uint8_t x1029_errorBehavior[CO_OD_CNT_ARR_1029];
    struct {
        uint8_t maxSub_index;
        uint32_t COB_IDClientToServer;
        uint32_t COB_IDServerToClient;
    } x1200_SDOServerParameter;
} CO_OD_ROM_t;

#ifndef CO_OD_ATTR_RAM
#define CO_OD_ATTR_RAM
#endif
extern CO_OD_ATTR_RAM CO_OD_RAM_t CO_OD_RAM;

#ifndef CO_OD_ATTR_ROM
#define CO_OD_ATTR_ROM
#endif
extern CO_OD_ATTR_ROM CO_OD_ROM_t CO_OD_ROM;

#ifndef CO_OD_ATTR_OD
#define CO_OD_ATTR_OD
#endif
extern CO_OD_ATTR_OD OD_t *CO_OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define CO_OD_ENTRY_H1000 &CO_OD->list[0]
#define CO_OD_ENTRY_H1001 &CO_OD->list[1]
#define CO_OD_ENTRY_H1002 &CO_OD->list[2]
#define CO_OD_ENTRY_H1003 &CO_OD->list[3]
#define CO_OD_ENTRY_H1005 &CO_OD->list[4]
#define CO_OD_ENTRY_H1006 &CO_OD->list[5]
#define CO_OD_ENTRY_H1007 &CO_OD->list[6]
#define CO_OD_ENTRY_H1008 &CO_OD->list[7]
#define CO_OD_ENTRY_H1009 &CO_OD->list[8]
#define CO_OD_ENTRY_H100A &CO_OD->list[9]
#define CO_OD_ENTRY_H100B &CO_OD->list[10]
#define CO_OD_ENTRY_H100C &CO_OD->list[11]
#define CO_OD_ENTRY_H100D &CO_OD->list[12]
#define CO_OD_ENTRY_H100E &CO_OD->list[13]
#define CO_OD_ENTRY_H1010 &CO_OD->list[14]
#define CO_OD_ENTRY_H1011 &CO_OD->list[15]
#define CO_OD_ENTRY_H1012 &CO_OD->list[16]
#define CO_OD_ENTRY_H1013 &CO_OD->list[17]
#define CO_OD_ENTRY_H1014 &CO_OD->list[18]
#define CO_OD_ENTRY_H1015 &CO_OD->list[19]
#define CO_OD_ENTRY_H1016 &CO_OD->list[20]
#define CO_OD_ENTRY_H1017 &CO_OD->list[21]
#define CO_OD_ENTRY_H1018 &CO_OD->list[22]
#define CO_OD_ENTRY_H1019 &CO_OD->list[23]
#define CO_OD_ENTRY_H1029 &CO_OD->list[24]
#define CO_OD_ENTRY_H1200 &CO_OD->list[25]
#define CO_OD_ENTRY_H1280 &CO_OD->list[26]
#define CO_OD_ENTRY_H1400 &CO_OD->list[27]
#define CO_OD_ENTRY_H1401 &CO_OD->list[28]
#define CO_OD_ENTRY_H1402 &CO_OD->list[29]
#define CO_OD_ENTRY_H1403 &CO_OD->list[30]
#define CO_OD_ENTRY_H1600 &CO_OD->list[31]
#define CO_OD_ENTRY_H1601 &CO_OD->list[32]
#define CO_OD_ENTRY_H1602 &CO_OD->list[33]
#define CO_OD_ENTRY_H1603 &CO_OD->list[34]
#define CO_OD_ENTRY_H1800 &CO_OD->list[35]
#define CO_OD_ENTRY_H1801 &CO_OD->list[36]
#define CO_OD_ENTRY_H1802 &CO_OD->list[37]
#define CO_OD_ENTRY_H1803 &CO_OD->list[38]
#define CO_OD_ENTRY_H1A00 &CO_OD->list[39]
#define CO_OD_ENTRY_H1A01 &CO_OD->list[40]
#define CO_OD_ENTRY_H1A02 &CO_OD->list[41]
#define CO_OD_ENTRY_H1A03 &CO_OD->list[42]
#define CO_OD_ENTRY_H1F80 &CO_OD->list[43]
#define CO_OD_ENTRY_H2000 &CO_OD->list[44]
#define CO_OD_ENTRY_H2001 &CO_OD->list[45]
#define CO_OD_ENTRY_H2002 &CO_OD->list[46]
#define CO_OD_ENTRY_H2003 &CO_OD->list[47]
#define CO_OD_ENTRY_H2004 &CO_OD->list[48]
#define CO_OD_ENTRY_H2010 &CO_OD->list[49]
#define CO_OD_ENTRY_H2011 &CO_OD->list[50]
#define CO_OD_ENTRY_H2012 &CO_OD->list[51]
#define CO_OD_ENTRY_H2100 &CO_OD->list[52]
#define CO_OD_ENTRY_H603F &CO_OD->list[53]
#define CO_OD_ENTRY_H6040 &CO_OD->list[54]
#define CO_OD_ENTRY_H6041 &CO_OD->list[55]
#define CO_OD_ENTRY_H6060 &CO_OD->list[56]
#define CO_OD_ENTRY_H6061 &CO_OD->list[57]
#define CO_OD_ENTRY_H6062 &CO_OD->list[58]
#define CO_OD_ENTRY_H6063 &CO_OD->list[59]
#define CO_OD_ENTRY_H6064 &CO_OD->list[60]
#define CO_OD_ENTRY_H6065 &CO_OD->list[61]
#define CO_OD_ENTRY_H6067 &CO_OD->list[62]
#define CO_OD_ENTRY_H606B &CO_OD->list[63]
#define CO_OD_ENTRY_H606C &CO_OD->list[64]
#define CO_OD_ENTRY_H606D &CO_OD->list[65]
#define CO_OD_ENTRY_H606F &CO_OD->list[66]
#define CO_OD_ENTRY_H6071 &CO_OD->list[67]
#define CO_OD_ENTRY_H6072 &CO_OD->list[68]
#define CO_OD_ENTRY_H6074 &CO_OD->list[69]
#define CO_OD_ENTRY_H6077 &CO_OD->list[70]
#define CO_OD_ENTRY_H607A &CO_OD->list[71]
#define CO_OD_ENTRY_H607C &CO_OD->list[72]
#define CO_OD_ENTRY_H607E &CO_OD->list[73]
#define CO_OD_ENTRY_H607F &CO_OD->list[74]
#define CO_OD_ENTRY_H6081 &CO_OD->list[75]
#define CO_OD_ENTRY_H6083 &CO_OD->list[76]
#define CO_OD_ENTRY_H6084 &CO_OD->list[77]
#define CO_OD_ENTRY_H6085 &CO_OD->list[78]
#define CO_OD_ENTRY_H6091 &CO_OD->list[79]
#define CO_OD_ENTRY_H6098 &CO_OD->list[80]
#define CO_OD_ENTRY_H6099 &CO_OD->list[81]
#define CO_OD_ENTRY_H60C0 &CO_OD->list[82]
#define CO_OD_ENTRY_H60C1 &CO_OD->list[83]
#define CO_OD_ENTRY_H60C2 &CO_OD->list[84]
#define CO_OD_ENTRY_H60C3 &CO_OD->list[85]
#define CO_OD_ENTRY_H60C4 &CO_OD->list[86]
#define CO_OD_ENTRY_H60E0 &CO_OD->list[87]
#define CO_OD_ENTRY_H60E1 &CO_OD->list[88]
#define CO_OD_ENTRY_H60F4 &CO_OD->list[89]
#define CO_OD_ENTRY_H60FC &CO_OD->list[90]
#define CO_OD_ENTRY_H60FD &CO_OD->list[91]
#define CO_OD_ENTRY_H60FF &CO_OD->list[92]
#define CO_OD_ENTRY_H6504 &CO_OD->list[93]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define CO_OD_ENTRY_H1000_deviceType &CO_OD->list[0]
#define CO_OD_ENTRY_H1001_errorRegister &CO_OD->list[1]
#define CO_OD_ENTRY_H1002_manufacturerStatusRegister &CO_OD->list[2]
#define CO_OD_ENTRY_H1003_pre_definedErrorField &CO_OD->list[3]
#define CO_OD_ENTRY_H1005_COB_ID_SYNC &CO_OD->list[4]
#define CO_OD_ENTRY_H1006_communicationCyclePeriod &CO_OD->list[5]
#define CO_OD_ENTRY_H1007_synchronousWindowLength &CO_OD->list[6]
#define CO_OD_ENTRY_H1008_manufacturerDeviceName &CO_OD->list[7]
#define CO_OD_ENTRY_H1009_manufacturerHardwareVersion &CO_OD->list[8]
#define CO_OD_ENTRY_H100A_manufacturerSoftwareVersion &CO_OD->list[9]
#define CO_OD_ENTRY_H100B_deviceID &CO_OD->list[10]
#define CO_OD_ENTRY_H100C_guardTime &CO_OD->list[11]
#define CO_OD_ENTRY_H100D_lifeTimeFactor &CO_OD->list[12]
#define CO_OD_ENTRY_H100E_nodeGuardingID &CO_OD->list[13]
#define CO_OD_ENTRY_H1010_storeParameters &CO_OD->list[14]
#define CO_OD_ENTRY_H1011_restoreDefaultParameters &CO_OD->list[15]
#define CO_OD_ENTRY_H1012_COB_ID_TIME &CO_OD->list[16]
#define CO_OD_ENTRY_H1013_highResolutionTimeStamp &CO_OD->list[17]
#define CO_OD_ENTRY_H1014_COB_ID_EMCY &CO_OD->list[18]
#define CO_OD_ENTRY_H1015_inhibitTimeEMCY &CO_OD->list[19]
#define CO_OD_ENTRY_H1016_consumerHeartbeatTime &CO_OD->list[20]
#define CO_OD_ENTRY_H1017_producerHeartbeatTime &CO_OD->list[21]
#define CO_OD_ENTRY_H1018_identityObject &CO_OD->list[22]
#define CO_OD_ENTRY_H1019_synchronousCounterOverflowValue &CO_OD->list[23]
#define CO_OD_ENTRY_H1029_errorBehavior &CO_OD->list[24]
#define CO_OD_ENTRY_H1200_SDOServerParameter &CO_OD->list[25]
#define CO_OD_ENTRY_H1280_SDOClientParameter &CO_OD->list[26]
#define CO_OD_ENTRY_H1400_receivePDO_CommunicationParameter0 &CO_OD->list[27]
#define CO_OD_ENTRY_H1401_receivePDO_CommunicationParameter1 &CO_OD->list[28]
#define CO_OD_ENTRY_H1402_receivePDO_CommunicationParameter2 &CO_OD->list[29]
#define CO_OD_ENTRY_H1403_receivePDO_CommunicationParameter3 &CO_OD->list[30]
#define CO_OD_ENTRY_H1600_receivePDO_MappingParameter0 &CO_OD->list[31]
#define CO_OD_ENTRY_H1601_receivePDO_MappingParameter1 &CO_OD->list[32]
#define CO_OD_ENTRY_H1602_receivePDO_MappingParameter2 &CO_OD->list[33]
#define CO_OD_ENTRY_H1603_receivePDO_MappingParameter3 &CO_OD->list[34]
#define CO_OD_ENTRY_H1800_transmitPDO_CommunicationParameter0 &CO_OD->list[35]
#define CO_OD_ENTRY_H1801_transmitPDO_CommunicationParameter1 &CO_OD->list[36]
#define CO_OD_ENTRY_H1802_transmitPDO_CommunicationParameter2 &CO_OD->list[37]
#define CO_OD_ENTRY_H1803_transmitPDO_CommunicationParameter3 &CO_OD->list[38]
#define CO_OD_ENTRY_H1A00_transmitPDO_MappingParameter0 &CO_OD->list[39]
#define CO_OD_ENTRY_H1A01_transmitPDO_MappingParameter1 &CO_OD->list[40]
#define CO_OD_ENTRY_H1A02_transmitPDO_MappingParameter2 &CO_OD->list[41]
#define CO_OD_ENTRY_H1A03_transmitPDO_MappingParameter3 &CO_OD->list[42]
#define CO_OD_ENTRY_H1F80_NMTStartup &CO_OD->list[43]
#define CO_OD_ENTRY_H2000_communicationSettings &CO_OD->list[44]
#define CO_OD_ENTRY_H2001_servoControl &CO_OD->list[45]
#define CO_OD_ENTRY_H2002_basicControlConfig &CO_OD->list[46]
#define CO_OD_ENTRY_H2003_motorSpecificSettings &CO_OD->list[47]
#define CO_OD_ENTRY_H2004_servoStatus &CO_OD->list[48]
#define CO_OD_ENTRY_H2010_torqueController &CO_OD->list[49]
#define CO_OD_ENTRY_H2011_velocityController &CO_OD->list[50]
#define CO_OD_ENTRY_H2012_positionController &CO_OD->list[51]
#define CO_OD_ENTRY_H2100_errorStatusBits &CO_OD->list[52]
#define CO_OD_ENTRY_H603F_errorCode &CO_OD->list[53]
#define CO_OD_ENTRY_H6040_controlword &CO_OD->list[54]
#define CO_OD_ENTRY_H6041_statusword &CO_OD->list[55]
#define CO_OD_ENTRY_H6060_modes_of_operation &CO_OD->list[56]
#define CO_OD_ENTRY_H6061_modesOfOperationDisplay &CO_OD->list[57]
#define CO_OD_ENTRY_H6062_positionDemandValue &CO_OD->list[58]
#define CO_OD_ENTRY_H6063_positionActualValueOfEncoder &CO_OD->list[59]
#define CO_OD_ENTRY_H6064_positionActualValue &CO_OD->list[60]
#define CO_OD_ENTRY_H6065_positionErrThreshold &CO_OD->list[61]
#define CO_OD_ENTRY_H6067_positionAtThreshold &CO_OD->list[62]
#define CO_OD_ENTRY_H606B_velocity_demand_value &CO_OD->list[63]
#define CO_OD_ENTRY_H606C_velocity_actual_value &CO_OD->list[64]
#define CO_OD_ENTRY_H606D_velocityAtThreshold &CO_OD->list[65]
#define CO_OD_ENTRY_H606F_velocityThreshold &CO_OD->list[66]
#define CO_OD_ENTRY_H6071_targetTorque &CO_OD->list[67]
#define CO_OD_ENTRY_H6072_maxTorque &CO_OD->list[68]
#define CO_OD_ENTRY_H6074_torqueDemand &CO_OD->list[69]
#define CO_OD_ENTRY_H6077_torqueActualValue &CO_OD->list[70]
#define CO_OD_ENTRY_H607A_target_position &CO_OD->list[71]
#define CO_OD_ENTRY_H607C_home_offset &CO_OD->list[72]
#define CO_OD_ENTRY_H607E_polarity &CO_OD->list[73]
#define CO_OD_ENTRY_H607F_max_velocity_limit &CO_OD->list[74]
#define CO_OD_ENTRY_H6081_profile_velocity &CO_OD->list[75]
#define CO_OD_ENTRY_H6083_profile_acceleration &CO_OD->list[76]
#define CO_OD_ENTRY_H6084_profile_deceleration &CO_OD->list[77]
#define CO_OD_ENTRY_H6085_quick_stop_deceleration &CO_OD->list[78]
#define CO_OD_ENTRY_H6091_gearRatio &CO_OD->list[79]
#define CO_OD_ENTRY_H6098_homing_method &CO_OD->list[80]
#define CO_OD_ENTRY_H6099_homing_speeds &CO_OD->list[81]
#define CO_OD_ENTRY_H60C0_interpolation_sub_mode_select &CO_OD->list[82]
#define CO_OD_ENTRY_H60C1_interpolation_data_record &CO_OD->list[83]
#define CO_OD_ENTRY_H60C2_interpolation_time_period &CO_OD->list[84]
#define CO_OD_ENTRY_H60C3_interpolation_sync_definition &CO_OD->list[85]
#define CO_OD_ENTRY_H60C4_interpolation_data_configuration &CO_OD->list[86]
#define CO_OD_ENTRY_H60E0_positiveTorqueLimitValue &CO_OD->list[87]
#define CO_OD_ENTRY_H60E1_negativeTorqueLimitValue &CO_OD->list[88]
#define CO_OD_ENTRY_H60F4_following_error_actual_value &CO_OD->list[89]
#define CO_OD_ENTRY_H60FC_position_demand_value &CO_OD->list[90]
#define CO_OD_ENTRY_H60FD_digital_inputs &CO_OD->list[91]
#define CO_OD_ENTRY_H60FF_target_velocity &CO_OD->list[92]
#define CO_OD_ENTRY_H6504_drive_manufacturer &CO_OD->list[93]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define CO_OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = 0;\
    (config).ENTRY_H1017 = CO_OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = 0;\
    (config).CNT_ARR_1016 = CO_OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = CO_OD_ENTRY_H1016;\
    (config).CNT_EM = 0;\
    (config).ENTRY_H1001 = CO_OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = CO_OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = CO_OD_ENTRY_H1015;\
    (config).CNT_ARR_1003 = CO_OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = CO_OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = 0;\
    (config).ENTRY_H1200 = CO_OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = 0;\
    (config).ENTRY_H1280 = CO_OD_ENTRY_H1280;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = CO_OD_ENTRY_H1012;\
    (config).CNT_SYNC = 0;\
    (config).ENTRY_H1005 = CO_OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = CO_OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = CO_OD_ENTRY_H1007;\
    (config).ENTRY_H1019 = CO_OD_ENTRY_H1019;\
    (config).CNT_RPDO = 0;\
    (config).ENTRY_H1400 = CO_OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = CO_OD_ENTRY_H1600;\
    (config).CNT_TPDO = 0;\
    (config).ENTRY_H1800 = CO_OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = CO_OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* CO_OD_H */
